### ISSUE TITLE
Feature Request: K/D, ADR, HS Rate etc.

### ISSUE THREAD

**Issue by TomHaupt** [SocksPls/hltv-api#15]
Hi,

first of all thank you for this cool scraper.
Would it be possible to get the K/D (Headshots) etc. for every map of a match?
for example:

https://www.hltv.org/stats/matches/65090/fnatic-vs-nip

thank you and greetings.

**Comment by zGrav** [comment]
Will do it if I manage to find the time or maybe @samgfw .

Thanks for the suggestion!

**Comment by zGrav** [comment]
Hey @TomHaupt to clarify this, you want each players K/D per map right?

**Comment by TomHaupt** [comment]
Yeah that would be awesome to get all stats of a match for every map.
Ive started to implement a bs4 code for that, maybe I can create a pull request when its done.

**Comment by r4phael** [comment]
great improvements... I'm following this issue :)

**Comment by zGrav** [comment]
Alright, if you hit a wall or simply no time @TomHaupt please tell me and I'll reopen this to do it myself.

**Comment by SocksPls** [comment]
Reopening since it has been over a year with no progress

**Comment by SocksPls** [comment]
https://github.com/SocksPls/hltv-api/commit/ae8333d43b0abcf6ba21e0ef558bfb0972f682d4
