### ISSUE TITLE
No issue - just a thanks!

### ISSUE THREAD

**Issue by Pigstah** [SocksPls/hltv-api#16]
Hey man,

Wasn't sure how to contact you, so thought this would be a good way!

I recently forked your HLTV API and used it a small starter project of mine and wanted to make sure you're happy with me using it? 

Also to say thank you for creating it! I was trying to do similar but my execution was no where near as good as yours!

Anyway hope everything is good for you, considering all that's going on!

If you want to get back to me, my email is matthew.pigram2@gmail.com

Take it easy!
Matthew

**Comment by zGrav** [comment]
Heya @Pigstah , from what it depends on me as a contributor to the project, this is fully open source, so feel free to use it.

Unless @SocksPls has any concerns about it?

**Comment by SocksPls** [comment]
Hi, I've added the AGPL v3 license, just follow that license and you're good :)
