### ISSUE TITLE
get_parsed_page() and get_matches() not working

### ISSUE THREAD

**Issue by bmargio** [SocksPls/hltv-api#24]
get_parsed_page seems to be getting blocked by cloudfare.

**Comment by zGrav** [comment]
CF blockage is usually on your end and cannot be solved by us.

Clean pull:
![image](https://user-images.githubusercontent.com/1788045/170824947-d1b026e8-8625-49e2-b7c3-f99fc9524c8e.png)

**Comment by SocksPls** [comment]
gonna drop this here https://github.com/FlareSolverr/FlareSolverr
