### ISSUE TITLE
URL appends bad string for event name in get_matches():

### ISSUE THREAD

**Issue by grantephross** [SocksPls/hltv-api#27]
py -3 .\HLTVbot.py
[{'date': '2022-06-01', 'url': '/matches/2356290/iem-dallas-2022-group-b-upper-bracket-semi-final-2-iem-dallas-2022', 'time': '02:00', 'event': b'ESL Challenger League Season 41 North America', 'team1': b'Unjustified', 'team2': b'ATK'}]

**Comment by grantephross** [comment]
its actually grabbing the wrong data entirely 

![image](https://user-images.githubusercontent.com/77510782/170923051-9fa408a7-ab12-484c-b379-53877e266848.png)

**Comment by zGrav** [comment]
good spot, fixed and pushed.

**Comment by grantephross** [comment]
Fix looks good, went through the output and I no longer see duplicates in the dictionary with matching ID numbers.
