### ISSUE TITLE
Matches by team id

### ISSUE THREAD

**Issue by EnKaizer** [SocksPls/hltv-api#37]
Hey guys, im trying to up a Pull Request, with this feature, if you guys likes it, i want to contribute with the project. but dont have permission.

the matches will displayed on `get_team_info` method, with a new property called `matches`, which give us, the id and name of both teams, the confront name, and the name of the event
```js
{ ...,
'matches': [{'championship': 'ESL Pro League Season 16',
              'confront_name': 'FURIA X Eternal Fire',
              'date': '21/09/2022',
              'full_time': '21/09/2022 at 16:00',
              'teams': {'team_1': 'FURIA',
                        'team_1_id': '8297',
                        'team_2': 'Eternal Fire',
                        'team_2_id': '11251'},
              'time': '16:00'},
             {'championship': 'ESL Pro League Season 16',
              'confront_name': 'FURIA X Movistar Riders',
              'date': '22/09/2022',
              'full_time': '22/09/2022 at 16:00',
              'teams': {'team_1': 'FURIA',
                        'team_1_id': '8297',
                        'team_2': 'Movistar Riders',
                        'team_2_id': '7718'},
              'time': '16:00'}],
 ...,
 }
```

**Comment by EnKaizer** [comment]
@zGrav  @grantephross

**Comment by grantephross** [comment]
can you make a pull with your commits to be reviewed?

**Comment by EnKaizer** [comment]
i tried, but received a 403
![image](https://user-images.githubusercontent.com/16261029/183965635-e0b452b1-a93c-495e-95d5-8e3a0c743174.png)

**Comment by EnKaizer** [comment]
@grantephross just tell me if you could give me the permission or i will need to make a fork for me

**Comment by SocksPls** [comment]
Hi @EnKaizer, try following this guide on creating a pull request so we can review your code

https://medium.com/geekculture/a-quick-guide-to-create-a-pull-request-on-github-80fc081b8a80

Thanks,
SocksPls

**Comment by EnKaizer** [comment]
@SocksPls @grantephross sorry about that, here is the PR:
https://github.com/SocksPls/hltv-api/pull/38

**Comment by zGrav** [comment]
Merged #38

**Comment by grantephross** [comment]
try making your own pull and committing your changes there then you can
make a merge request

i think that's how i did it

**Comment by grantephross** [comment]
I can't, it isn't my project.
