### ISSUE TITLE
Failed to get parsed page

### ISSUE THREAD

**Issue by Helyux** [SocksPls/hltv-api#40]
This does not work anymore does it?
Looks like the cloudflare protection got increased.

`get_parsed_page` returns:

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="noindex,nofollow" name="robots"/>
<meta content="width=device-width,initial-scale=1" name="viewport"/>
<link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"/>
</head>
<body class="no-js">
<div class="main-wrapper" role="main">
<div class="main-content">
<h1 class="zone-name-title h1">
<img alt="Icon for www.hltv.org" class="heading-favicon" onerror="this.onerror=null;this.parentNode.removeChild(this)" src="/favicon.ico"/>
            www.hltv.org
        </h1>
<h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
<noscript>
<div id="challenge-error-title">
<div class="h2">
<span class="icon-wrapper">
<div class="heading-icon warning-icon"></div>
</span>
<span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
</div>
</div>
</noscript>
<div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7ab6f3989b74aca4')"></div>
<div class="core-msg spacer" id="challenge-body-text">
            www.hltv.org needs to review the security of your connection before proceeding.
        </div>

**Comment by SocksPls** [comment]
Hi,

I've tested the current implementation, and it works for me. However, it's possible that the Cloudflare protection has been updated for some users or regions.

If you're still facing issues, you might want to try using [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr). It's a standalone app designed to help bypass Cloudflare challenges, and it might be helpful in your case. You can integrate it into your project and see if it resolves the issue for you.

Let me know if you have any questions or need further assistance.

**Comment by Helyux** [comment]
Hi SocksPls, 
thanks for the pointer, i'll try to implement FlareSolverr into my project.
Feel free to close this issue.
